### ISSUE TITLE
Home base #3

### ISSUE THREAD

**Issue by DrPiggy** [evodz/shabak#1]
Hey, i got to home base #3, and im a little struggling to create something that won't take 3 days to run, i thought i could get hints from your code but the link you give goes to a blank mp4 file?

**Comment by evodz** [comment]
Since the size is so small you need to download the first video. I have uploaded another video @DrPiggy at https://p.lewd.es/foqejb.mp4 showing the inner workings of how I can brute force it so fast.

**Comment by DrPiggy** [comment]
@evodz oh, i thought your gonna show the code, which would let me search for hints, because im currently stuck, my way is actual brute force with some heuristics to optimize it, i cant find a way which will not take 3 days to run on my old cpu

**Comment by evodz** [comment]
I won't spoon feed anyone through it; that is how life works. I was hinting at doing pairs of 2 or 3 at a time then checking it against the characters mentioned (https://i.imgur.com/cwZb0xP.png). You can go further and compare pairs of two to a 2 letter word list, rainbow table, assuming that the encrypted was a sentence, which it is. You could also do an analysis before chunking and see word results like so (https://i.imgur.com/cIJrfgq.png) (https://i.imgur.com/GbR3Vgz.png) that can guide you through bruteforcing. If you bruteforce the entire encrypted string without any guidance from pre-analysis or a rainbow table you will be stuck. An example to try for understanding would be to do their example in the second challenge and match "gghh" with "ffff".

**Comment by evodz** [comment]
A good friend of mine has started to upload his version of the challenge. He is willing to provide all of the sources to the challenges you are looking for with more detail.

https://github.com/VirtualPuppet/shabak-challenge
